# Generated by Django 5.2.12 on 2026-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
